export const navesList =[
    { id: 1,  nombre: "Rattlesnake", precio: " 4500", tipo:"Acorazado",     imagen: 'https://wiki.eveuniversity.org/images/thumb/0/0f/Rattlesnake.jpg/256px-Rattlesnake.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 2,  nombre: "Machariel",   precio: " 3800", tipo:"Acorazado",     imagen: 'https://wiki.eveuniversity.org/images/thumb/1/14/Machariel.jpg/256px-Machariel.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 3,  nombre: "Bhaalgorn",   precio: " 4900", tipo:"Acorazado",     imagen: 'https://wiki.eveuniversity.org/images/thumb/e/ec/Bhaalgorn.jpg/256px-Bhaalgorn.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 4,  nombre: "Nestor",      precio: "21900", tipo:"Acorazado",     imagen: 'https://wiki.eveuniversity.org/images/thumb/7/70/Nestor.jpg/256px-Nestor.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 5,  nombre: "Barghest",    precio: "23000", tipo:"Acorazado",     imagen: 'https://wiki.eveuniversity.org/images/thumb/b/bb/Barghest.jpg/256px-Barghest.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 6,  nombre: "Nightmare",   precio: " 5000", tipo:"Acorazado",     imagen: 'https://wiki.eveuniversity.org/images/thumb/3/38/Nightmare.jpg/256px-Nightmare.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 7,  nombre: "Vindicator",  precio: " 4600", tipo:"Acorazado",     imagen: 'https://wiki.eveuniversity.org/images/thumb/4/49/Vindicator.jpg/256px-Vindicator.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 8,  nombre: "Apocalypse Strike", precio: "19000", tipo:"Acorazado",imagen: 'https://wiki.eveuniversity.org/images/thumb/1/13/Apocalypse.jpg/256px-Apocalypse.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 9,  nombre: "Gila",       precio: "1050", tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/b/b9/Gila.jpg/256px-Gila.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 10, nombre: "Cynabal",    precio: "800",  tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/f/f8/Cynabal.jpg/256px-Cynabal.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 11, nombre: "Ashimmu",    precio: "1150", tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/b/ba/Ashimmu.jpg/256px-Ashimmu.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 12, nombre: "Stratios",   precio: "3200", tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/2/2d/Stratios.jpg/256px-Stratios.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 13, nombre: "Orthrus",    precio: "2900", tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/1/1a/Orthrus.jpg/256px-Orthrus.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 14, nombre: "Phantasm",   precio: "1000", tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/5/5f/Phantasm.jpg/256px-Phantasm.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 15, nombre: "Vigilant",   precio: "1000", tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/7/7e/Vigilant.jpg/256px-Vigilant.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 16, nombre: "Scythe  ",   precio: "54",   tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/3/37/Scythe.jpg/256px-Scythe.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 17, nombre: "Augoror  ",  precio: "58",   tipo:"Crucero",       imagen: 'https://wiki.eveuniversity.org/images/thumb/0/01/Augoror.jpg/256px-Augoror.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 18, nombre: "rupture Guardian II", precio: "78", tipo:"Crucero", imagen: 'https://wiki.eveuniversity.org/images/thumb/8/8b/Rupture.jpg/256px-Rupture.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 19, nombre: "Maller Guardian II", precio: "100", tipo:"Crucero", imagen: 'https://wiki.eveuniversity.org/images/thumb/f/fe/Maller.jpg/256px-Maller.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 20, nombre: "arbitrator Interdiccion", precio: "100", tipo:"Crucero", imagen: 'https://wiki.eveuniversity.org/images/thumb/7/72/Arbitrator.jpg/256px-Arbitrator.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 21, nombre: "Worm",      precio: "210",  tipo:"Fragata",       imagen: 'https://wiki.eveuniversity.org/images/thumb/d/d8/Worm.jpg/256px-Worm.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 22, nombre: "Dramiel",   precio: "190",  tipo:"Fragata",       imagen: 'https://wiki.eveuniversity.org/images/thumb/3/38/Dramiel.jpg/256px-Dramiel.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 23, nombre: "Cruor",     precio: "225",  tipo:"Fragata",       imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq2TKcHWFGzmKzr3ebavCX3zyC_4VKgnw-5dN5dqWCY--Q9WtTZYBVzHnvJZfxGpawnG4&usqp=CAU', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 24, nombre: "Astero",    precio: "750",  tipo:"Fragata",       imagen: 'https://wiki.eveuniversity.org/images/thumb/5/50/Astero.jpg/256px-Astero.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 25, nombre: "Garmur",    precio: "700",  tipo:"Fragata",       imagen: 'https://wiki.eveuniversity.org/images/thumb/6/62/Garmur.jpg/256px-Garmur.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 26, nombre: "Succubus",  precio: "218",  tipo:"Fragata",       imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ3AjZDD5bdh30VW-GehmTA7S06NkhX_MNPmrGpIoFneRbIJL13cZoDRljPrvo42p7BYo&usqp=CAU', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 27, nombre: "daredevil", precio: "215",  tipo:"Fragata",       imagen: 'https://wiki.eveuniversity.org/images/thumb/7/7f/Daredevil.jpg/256px-Daredevil.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 28, nombre: "Condor Interceptacion 2",   precio: "230", tipo:"Fragata", imagen: 'https://wiki.eveuniversity.org/images/thumb/d/d5/Condor.jpg/256px-Condor.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 29, nombre: "Heron Scout",               precio: "225", tipo:"Fragata", imagen: 'https://wiki.eveuniversity.org/images/thumb/f/f3/Heron.jpg/256px-Heron.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 30, nombre: "Cormorant Interdiccion II", precio: "170", tipo:"Destructor", imagen: 'https://wiki.eveuniversity.org/images/thumb/f/fb/Cormorant.jpg/256px-Cormorant.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 31, nombre: "Thrasher Interdiccion",     precio: "50",  tipo:"Destructor", imagen: 'https://imageserver.eveonline.com/Render/33883_512.png', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 32, nombre: "Algos de Asalto",     precio: "75",  tipo:"Destructor", imagen: 'https://wiki.eveuniversity.org/images/thumb/9/98/Algos.jpg/256px-Algos.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 33, nombre: "Dragoon de Asalto",   precio: "75",  tipo:"Destructor", imagen: 'https://wiki.eveuniversity.org/images/thumb/7/78/Dragoon.jpg/256px-Dragoon.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 34, nombre: "Corax de Asalto",     precio: "75",  tipo:"Destructor", imagen: 'https://image.eveonline.com/Render/32876_512.png', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 35, nombre: "Ferox Guardian",      precio: "280", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado2.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 36, nombre: "Prophecy Guardian",   precio: "270", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 37, nombre: "Hurricane Logistica", precio: "290", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 38, nombre: "Brutix Logistica",    precio: "230", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado1.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 39, nombre: "Prophecy",    precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado2.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 40, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 41, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 42, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 43, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 44, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 45, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 46, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 47, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 48, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 49, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
    { id: 50, nombre: "Harbinger",   precio: "250", tipo:"C. de Batalla", imagen: '../../assets/imagen/acorazado3.jpg', stock: 7, descripcion: "es una nave de rapida y versatil, perfecta para las fratas y naves capitales"},
]

export const getFetchNaves = new Promise((resolve, reject)=>{
    setTimeout(()=>{ resolve(navesList) }, 1000)
})

export const getFetchUnaNave = new Promise((resolve, reject)=>{
    setTimeout(()=>{ resolve(navesList) }, 1000)
})


